urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2015 Slack
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^contact/', include('contact.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^', include('descgen.urls'))
)

descgen/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2015 Slack
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.db.models.signals import m2m_changed, post_delete, post_save, pre_delete
from django.db.models.query import Q
from django.db.models import Max

from .scraper.factory import SCRAPER_CHOICES


class PublicTemplateManager(models.Manager):

    def get_queryset(self):
        return super(PublicTemplateManager, self).get_queryset().filter(Q(is_default__exact=True) | Q(is_public__exact=True))


class Template(models.Model):

    owner = models.ForeignKey(User)
    name = models.CharField(max_length=40,
                            help_text='Enter the name of the template here.')
    template = models.TextField(validators=[MaxLengthValidator(8192)], blank=True, help_text='Enter the template code here.')
    is_public = models.BooleanField(default=False,
                                    help_text='Make this template public. Public templates can be used by all users that are subscribed to you.')
    is_default = models.BooleanField(default=False,
                                     help_text='Make this template a default. Default templates can be used by all registered users and users that are not logged in.')
    is_utility = models.BooleanField(default=False,
                                     help_text="Mark this template as a utility. Utility templates are only used as the basis for other templates and won't appear in the list of available templates for rendering a release directly.")
    dependencies = models.ManyToManyField('self', symmetrical=False, related_name='depending_set', blank=True,
                                          help_text='Choose which templates this template depends on. Chosen templates can be included or extended in your template code.')

    objects = models.Manager()
    public_templates = PublicTemplateManager()

    def __unicode__(self):
        out = self.name
        if not self.is_default:
            out += u' [%s]' % self.owner.username
        return out

    def visible_to_user(self, user, assume_subscription=False):
        if user is None:
            return self.is_default
        else:
            if assume_subscription:
                return self.is_default or self.owner_id == user.id or self.is_public
            else:
                return self.is_default or self.owner_id == user.id or (self.owner.subscriber_set.filter(subscriber__exact=user).exists() and self.is_public)

    @property
    def is_visible(self):
        return self.is_default or self.is_public

    def get_unique_name(self):
        return 'template_%d' % self.pk

    def depends_on(self):
        return u', '.join(map(unicode, self.dependencies.all()))

    def dependencies_set(self):
        res = set()
        for f in self.dependencies.all():
            res.add(f)
            res.update(f.dependencies_set())
        return res

    def cached_dependencies_set(self, prefetch_owner=False):
        res = set()
        l = DependencyClosure.objects.filter(descendant__exact=self, path_length__gt=0).values('ancestor_id').distinct()
        q = Template.objects.filter(id__in=l)
        if prefetch_owner:
            q = q.select_related('owner')
        for f in q:
            res.add(f)
        return res

    def max_dependency_height(self, include_descendants):
        aggregate = DependencyClosure.objects.filter(descendant__exact=self).aggregate(max_height=Max('path_length'))
        height = aggregate['max_height']
        if include_descendants:
            aggregate = DependencyClosure.objects.filter(ancestor__exact=self).aggregate(max_height=Max('path_length'))
            height += aggregate['max_height']
        return height

    def depending_templates_requiring_public(self):
        return self.depending_set.filter(~Q(owner_id__exact=self.owner_id) | Q(owner_id__exact=self.owner_id, is_public__exact=True))

    @staticmethod
    def circular_checker(parent, child):
        """
        Checks that the object is not an ancestor or a descendant,
        avoid self links
        """
        if parent == child:
            raise ValidationError('A template may not depend on itself.')
        # child is only hashable if the primary key is set; child has to be hashable in order to check whether
        # it is part of the dependency set, so only check for this if pk is set
        # an empty pk means that child is not yet saved in the database and therefore cannot be a dependency for parent
        if child.pk and child in parent.dependencies_set():
            raise ValidationError('One of the dependencies has a dependency on this template.')

    @staticmethod
    def templates_for_user(user, with_utility=True, sort_by_name=False, prefetch_owner=False):
        if user is not None and user.is_authenticated():
            subscribed_to = user.subscribed_to.values('user_id').distinct()
            t = Template.objects.filter(Q(owner__in=subscribed_to, is_public__exact=True) | Q(owner__exact=user.pk) | Q(is_default__exact=True))
        else:
            t = Template.objects.filter(is_default__exact=True)
        if not with_utility:
            t = t.filter(is_utility__exact=False)
        if prefetch_owner:
            t = t.select_related('owner')
        if sort_by_name:
            t = t.extra(select={'lower_name': 'lower(name)'}).order_by('lower_name')
        return t

    class Meta:
        unique_together = ('owner', 'name')


class DependencyClosure(models.Model):

    descendant = models.ForeignKey(Template, related_name='closure_descendant')
    ancestor = models.ForeignKey(Template, related_name='closure_ancestor')
    path_length = models.IntegerField()
    count = models.IntegerField()

    class Meta:
        unique_together = ('descendant', 'ancestor', 'path_length')

    def __unicode__(self):
        return u'%s depends on %s over %d hops' % (self.descendant, self.ancestor, self.path_length)


def dependency_changed(sender, **kwargs):
    """
    This method for updating the dependency closures assumes that only the forward relation for the many-to-many field
    is ever modified, i.e. template.dependencies.add(other_template) and never other_template.depending_set.add(template)
    """
    action = kwargs['action']
    if action == 'post_add':
        instance = kwargs['instance']
        pk_set = kwargs['pk_set']
        # get all templates that depend on the we one that was modified and are at least one hop away (exclude the self
        # links)
        modified_instance_descendants = DependencyClosure.objects.filter(ancestor_id__exact=instance.pk, path_length__gt=0)
        for pk in pk_set:
            # for every added dependency and it's dependencies we add a new path from the modified instance
            current_pk_ancestors = DependencyClosure.objects.filter(descendant_id__exact=pk)
            for current_pk_ancestor in current_pk_ancestors:
                # old situation:   pk --> ... --> current_pk_ancestor
                #                     \         /
                #                     path_length
                #
                # new situation:   instance --> pk --> ... --> current_pk_ancestor
                #                           \               /
                #                            path_length + 1
                #
                # Note: every template automatically has the path:         pk --
                #                                                           ^   \  length = 0
                #                                                            \__/
                #       so the path    instance --> pk   with length 1
                #       will be added without the need for any special corner case handling
                try:
                    # see if we already have a path from instance to current_pk_ancestor with the expected length
                    path_to_ancestor = DependencyClosure.objects.get(descendant_id__exact=instance.pk, ancestor_id__exact=current_pk_ancestor.ancestor_id, path_length=current_pk_ancestor.path_length+1)
                except DependencyClosure.DoesNotExist:
                    # if we don't create one
                    path_to_ancestor = DependencyClosure.objects.create(descendant_id=instance.pk, ancestor_id=current_pk_ancestor.ancestor_id, path_length=current_pk_ancestor.path_length+1, count=current_pk_ancestor.count)
                else:
                    # otherwise increase the count to include the new paths
                    path_to_ancestor.count += current_pk_ancestor.count
                    path_to_ancestor.save()

                # now we have to add the new path to all descendants of the modified instance
                #

templates/base.html
{% load static %}{% load scrapernames %}{% scraper_names as SCRAPER_NAMES %}<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}YADG</title>
    <meta charset="utf-8">
    <meta name="description" content="Extract release information from {% for scraper_name in SCRAPER_NAMES %}{{ scraper_name }}{% if forloop.counter < SCRAPER_NAMES|length|add:"-1" %}, {% else %}{% if forloop.counter == SCRAPER_NAMES|length|add:"-1" %} or {% endif %}{% endif %}{% empty %}nowhere right now{% endfor %} and create a nice description from it." />
    <meta name="keywords" content="description, generator{% if not SCRAPER_NAMES|length_is:"0" %}, {% endif %}{% for scraper_name in SCRAPER_NAMES %}{{ scraper_name|lower }}{% if not forloop.last %}, {% endif %}{% endfor %}" />
    <link rel="icon" href="{% static "img/favicon.ico" %}" type="image/x-icon" />
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <style>
      ul#release_list li {
        margin-bottom: .9em;
      }

      #description_area {
        width: 100%;
        height: 500px;
      }

      #result_permalink_input {
        width: 100%;
      }

      .center {
        display: block;
        text-align: center;
        margin: 20px auto;
      }

      html.jquery-js-enabled button#format_submit {
        display: none !important;
      }

      .auto_width {
        width: auto;
      }

      .input-xhlarge{
        width: 400px;
      }

      .input-automax {
        width: auto;
        max-width: 100%;
      }

      .clear {
        clear: both;
      }
    </style>

    <script src="{% static "js/jquery-1.8.0.min.js" %}"></script>
    <script src="{% static "js/bootstrap-tooltip.min.js" %}"></script>
    <script src="{% static "js/bootstrap-dropdown.min.js" %}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('html').addClass('jquery-js-enabled');

            $('#id_template').change(function(e) {
                e.preventDefault();
                $('#format_form').submit();
            });

            $('.yadg_tooltip').tooltip();
        });
    </script>

    {% block additionalHeaders %}{% endblock %}
</head>

  <body>
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="{% url 'index' %}" title="Yet Another Description Generator">YADG</a>
          <ul class="nav">
            <li{% block home_li_tags %} class="active"{% endblock %}><a href="{% url 'index' %}">Home</a></li>
            <li{% block scrapers_li_tags %}{% endblock %}><a href="{% url 'scrapers_overview' %}">Available Scrapers</a></li>
            {% if user.is_authenticated %}<li{% block userlist_li_tags %}{% endblock %}><a href="{% url 'user_list' %}">Users</a></li>
            <li{% block scratchpad_li_tags %}{% endblock %}><a href="{% url 'scratchpad_index' %}">Scratchpad</a></li>{% endif %}
            <li><a href="{% url 'api_root' %}">API</a></li>
            <li{% block contact_li_tags %}{% endblock %}><a href="{% url 'contact' %}">Contact</a></li>
          </ul>
          <ul class="nav pull-right">
              {% if user.is_authenticated %}
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li{% block userpage_li_tags %}{% endblock %}><a href="{% url 'user_detail' user.pk %}">My user page</a></li>
                    <li{% block templatelist_li_tags %}{% endblock %}><a href="{% url 'template_list' %}">My templates</a></li>
                    <li{% block subscriptions_li_tags %}{% endblock %}><a href="{% url 'subscriptions' %}">My subscriptions</a></li>
                    <li class="divider"></li>
                    <li{% block passwordchange_li_tags %}{% endblock %}><a href="{% url 'password_change' %}">Change password</a></li>
                    <li{% block settings_li_tags %}{% endblock %}><a href="{% url 'settings' %}">Settings</a></li>
                </ul>
              </li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                  <li{% block register_li_tags %}{% endblock %}><a href="{% url 'register' %}">Register</a></li>
                  <li{% block login_li_tags %}{% endblock %}><a href="{% url 'login' %}">Login</a></li>
              {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <noscript><div class="alert alert-warning"><strong>Heads up!</strong> Javascript seems to be disabled for this website. This website makes heavy use of javascript and will not work correctly without it.</div></noscript>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/base_with_form.html
{% extends "base.html" %}

{% block additionalHeaders %}<script type="text/javascript">
    $(document).ready(function() {
        $('#result_permalink_input').focus(function(e) {
            e.preventDefault();
            $(this).select();
        });
    });
</script>
{% endblock %}

{% block content %}{% include "input_form.html" %}
<div id="subcontent">{% block subcontent %}{% endblock %}</div>{% endblock %}

templates/bootstrap_form_fields.html
{% for field in form %}
    <div class="control-group{% if field.errors %} error{% endif %}">
        <label for="id_{{ field.html_name }}" class="control-label">{{ field.label }}</label>
        <div class="controls">
            {{ field }}
            {% if field.errors %}
                {% if field.errors|length_is:1 %}
                    <span class="help-inline">{{ field.errors|first|escape }}</span>
                {% else %}
                    <ul class="help-block">
                        {% for error in field.errors %}
                        <li>{{ error|escape }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endif %}
            {% if field.help_text %}<p class="help-block">{{ field.help_text }}</p>{% endif %}
        </div>
    </div>
{% endfor %}

templates/dependency_codes.html
{% regroup immediate_dependencies|dictsort:"owner.username.lower" by owner as grouped_dependencies %}
<h2>Dependencies <a class="yadg_tooltip" href="#" title="The list of templates that are available to be included by this template's code. Each entry lists the name of the user the accessible template belongs to, it's name (in bold letters) and below that the id which can be used to refer to the template in code.">[?]</a>:</h2>
<dl style="overflow-x: auto;">
    {% for group in grouped_dependencies %}
        <dt>by {% if group.grouper.pk == user.pk %}{{ group.grouper }} (you){% else %}<a href="{% url 'user_detail' group.grouper.pk %}">{{ group.grouper }}</a>{% endif %}:</dt>
        <dd>
            {% block dependency_codes_list_dd %}{% endblock %}
        </dd>
    {% endfor %}
</dl>

templates/format_form.html
<form action="{{ request.path }}" method="get" class="form-inline{% if form_classes %} {{ form_classes }}{% endif %}" id="format_form">
{{ format_form.template.label_tag }} {{ format_form.template }}
<button type="submit" class="btn" id="format_submit">Go</button>
</form>

templates/input_form.html
{% load addforms %}{% if not input_form %}{% add_input_form as input_form %}{% endif %}<form action="{% url 'index' %}" method="get" class="form-inline well">
  {{ input_form.input.label_tag }} {{ input_form.input }}
  {{ input_form.scraper.label_tag }}
  {{ input_form.scraper }}
  <button type="submit" class="btn btn-primary" id="submit">Fetch</button>
</form>

templates/paginator.html
<div class="pagination pagination-centered">
    <ul>
    {% if page_obj.has_previous %}<li><a href="{{ base_url }}page={{ page_obj.previous_page_number }}">←</a></li>{% endif %}
    {% if show_first %}<li><a href="{{ base_url }}page=1">1</a></li>
    <li class="disabled"><a href="#">...</a></li>{% endif %}
    {% for num in page_numbers %}
    {% if page_obj.number == num %}<li class="active"><a href="#">{{ num }}</a></li>{% else %}<li><a href="{{ base_url }}page={{ num }}">{{ num }}</a></li>{% endif %}
    {% endfor %}
    {% if show_last %}<li class="disabled"><a href="#">...</a></li>
    <li><a href="{{ base_url }}page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>{% endif %}
    {% if page_obj.has_next %}<li><a href="{{ base_url }}page={{ page_obj.next_page_number }}">→</a></li>{% endif %}
    </ul>
</div>

templates/sandbox_rendering_headers.html
{% load static %}<link rel="jsandbox" href="{% static "js/jsandbox-worker.js" %}" />
<script src="{% static "js/jsandbox.min.js" %}"></script>

templates/template_edit_public_warning.html
{% if template and not template.is_default and template.is_public and template.depending_templates_requiring_public.exists %}
    <div class="alert alert-warning">
        <strong>Warning!</strong> You are editing a public template which has at least one other template depending on it that is either
        <ul>
            <li>owned by another user or</li>
            <li>owned by you and public at the same time.</li>
        </ul>
        Making this template private will <strong>remove all these dependencies irreversibly</strong>. Dependencies from non-public templates owned by you will not be affected.
    </div>
{% endif %}