urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2015 Slack
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^contact/', include('contact.urls')),

    url(r'^admin/', include(admin.site.urls)),
    
    url(r'^', include('descgen.urls'))
)

descgen/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2015 Slack
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django import forms
from descgen.scraper.factory import SCRAPER_CHOICES,SCRAPER_DEFAULT
from .models import Template, Subscription, Settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db.models.query import Q
from django.core.exceptions import ValidationError
from codemirror import CodeMirrorTextarea
from captcha.fields import ReCaptchaField
import operator

search_form_widget_kwargs = {
    'attrs': {
        'class': 'input-medium search-query',
        'placeholder': 'leave empty for all'
    }
}

template_code_widget_kwargs = {
    'keymap': 'yadg',
    'mode': 'swig',
    'config': {
        'lineWrapping': True,
        'lineNumbers': True,
        'styleActiveLine': True
    },
    'theme': 'neo'
}


class InputForm(forms.Form):
    input = forms.CharField(label='Input:', max_length=1000, widget=forms.TextInput(attrs={'placeholder': 'Enter release url or search term','class':'input-xhlarge'}))
    scraper = forms.ChoiceField(required=False, label='Scraper:', choices=SCRAPER_CHOICES, initial=SCRAPER_DEFAULT, widget=forms.Select(attrs={'class':'auto_width'}))


class FormatForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        with_utility = kwargs.get('with_utility', False)
        if 'with_utility' in kwargs:
            del kwargs['with_utility']
        default_template = kwargs.get('default_template', None)
        if 'default_template' in kwargs:
            del kwargs['default_template']
        if default_template is not None:
            default_template = default_template.pk
        super(FormatForm, self).__init__(*args, **kwargs)
        self.fields['template'] = forms.TypedChoiceField(coerce=int, label='Template:',
                                                    choices=map(lambda x: (x.pk, unicode(x)),
                                                                # todo: investigate whether prefetching the owner name actually has higher performance here
                                                                Template.templates_for_user(user, with_utility=with_utility, sort_by_name=True, prefetch_owner=True)),
                                                    widget=forms.Select(attrs={'class': 'auto_width'}), initial=default_template)


class ApiTokenForm(forms.Form):
    action = forms.ChoiceField(choices=[('new', 'new')], initial='new', widget=forms.HiddenInput)


class SettingsAdminForm(forms.ModelForm):

    class Meta:
        model = Settings
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        prefetch_owner = kwargs.get('prefetch_owner', True)
        if 'prefetch_owner' in kwargs:
            del kwargs['prefetch_owner']
        super(SettingsAdminForm, self).__init__(*args, **kwargs)
        t = Template.templates_for_user(self.instance.user if self.instance else None, with_utility=False, sort_by_name=True, prefetch_owner=prefetch_owner)
        self.fields['default_template'].queryset = t

    def clean_user(self):
        user = self.cleaned_data['user']

        if user is None:
            try:
                default_settings = Settings.objects.get(user__isnull=True)
            except Settings.DoesNotExist:
                default_settings = None
            if default_settings is not None and self.instance != default_settings:
                raise ValidationError('Only one settings object with a blank user is allowed at any given time.')

        return user


class SettingsForm(SettingsAdminForm):

    empty_label = '--- Site default'

    class Meta(SettingsAdminForm.Meta):
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        super(SettingsForm, self).__init__(*args, **kwargs)
        self.fields['default_template'].empty_label = self.empty_label
        self.fields['default_scraper'].choices = [("", self.empty_label)] + list(self.fields["default_scraper"].choices)[1:] # todo: replace this ugly hack when switching to Django 1.7


class UserSearchForm(forms.Form):
    username = forms.CharField(label='User: ', required=False, max_length=30, widget=forms.TextInput(**search_form_widget_kwargs))
    template_name = forms.CharField(label='with template: ', required=False, max_length=40, widget=forms.TextInput(**search_form_widget_kwargs))


class SubscribeForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput)

    def clean_user_id(self):
        user_id = self.cleaned_data['user_id']
        try:
            User.objects.get(pk=user_id)
        except User.DoesNotExist:
            raise ValidationError('No valid user id specified')
        return user_id


class UnsubscribeForm(forms.Form):
    next = forms.CharField(widget=forms.HiddenInput, required=False)
    user_id = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        self.subscriber = kwargs['subscriber']
        kwargs.pop('subscriber')
        super(UnsubscribeForm, self).__init__(*args, **kwargs)

    def clean_user_id(self):
        user_id = self.cleaned_data['user_id']
        try:
            User.objects.get(pk=user_id)
        except User.DoesNotExist:
            raise ValidationError('No valid user id specified')
        if not Subscription.objects.filter(subscriber_id__exact=self.subscriber.pk, user_id__exact=user_id).exists():
            raise ValidationError('You cannot unsubscribe from a user you are not subscribed to.')
        return user_id


class TemplateAdminForm(forms.ModelForm):

    class Meta:
        model = Template
        fields = '__all__'
        widgets = {
            'template': CodeMirrorTextarea(**template_code_widget_kwargs),
            'dependencies': forms.SelectMultiple(attrs={'class': 'input-automax'})
        }

    def __init__(self, *args, **kwargs):
        # todo: investigate whether prefetching the owner name here by default is actually a good idea
        prefetch_owner = kwargs.get('prefetch_owner', True)
        if 'prefetch_owner' in kwargs:
            del kwargs['prefetch_owner']
        super(TemplateAdminForm, self).__init__(*args, **kwargs)
        t = Template.objects.none()
        if self.instance:
            try:
                u = self.instance.owner
            except User.DoesNotExist:
                pass
            else:
                t = Template.templates_for_user(u, sort_by_name=True, prefetch_owner=prefetch_owner)
        self.fields['dependencies'].queryset = t

    def clean(self):
        cleaned_data = super(TemplateAdminForm, self).clean()

        dependency_errors = []
        dependencies = cleaned_data.get('dependencies', None)
        if dependencies is not None:
            # make sure there are no circular dependencies
            for dep in dependencies:
                try:
                    Template.circular_checker(dep, self.instance)
                except ValidationError as e:
                    dependency_errors = e.messages

            # make sure dependencies are either public templates of users subscribed to or own templates
            owner = cleaned_data.get('owner', None)
            if owner is None and self.instance:
                try:
                    owner = self.instance.owner
                except User.DoesNotExist:
                    pass
            if owner:
                t = Template.templates_for_user(owner)
            else:
                t = Template.objects.none()

            if any([(not x in t) for x in dependencies]):
                msg = 'A template may only depend on own templates or public templates of users you are subscribed to.'
                dependency_errors.append(msg)

            # TODO: if it becomes a problem restrict the maximum height of a dependency graph (descendants + ancestors)
            # make sure the total number of ancestors in the new dependency graph is not too great
            max_elements = 50
            all_elements = reduce(operator.or_, map(lambda x: x.cached_dependencies_set(), dependencies), set(dependencies))
            num_elements = len(all_elements)
            if num_elements > max_elements:
                msg = "The total number of ancestors in the dependency graph is %d. It mustn't be greater than %d." % (num_elements, max_elements)
                dependency_errors.append(msg)

        if dependency_errors:
            self.add_error('dependencies', dependency_errors)

        # make sure a public template only has public dependencies
        is_public = cleaned_data.get('is_public', None)
        if is_public is not None and dependencies is not None:
            if is_public and any([not x.is_public for x in dependencies]):
                msg = 'A template may only be public if all of its dependencies are public.'
                self.add_error('is_public', msg)

templates/user/subscribe_form.html
<form action="{% url 'subscribe_to_user' %}?next={{ request.path }}{% if get_query_string %}%3F{{ get_query_string }}{% endif %}" method="post" class="pull-right" id="subscribe_form_{{ sub_user.pk }}">
    {% csrf_token %}
    {{ subscribe_form }}
    <button type="submit" class="btn btn-success" id="subscribe_submit_{{ sub_user.pk }}" title="Subscribing to a user grants access to all of their public templates.">Subscribe</button>
</form>

templates/user/subscriptions.html
{% extends "base.html" %}

{% block title%}My subscriptions – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block subscriptions_li_tags %} class="active"{% endblock %}

{% block additionalHeaders %}
    <style>
        tr td:last-child {
            width: .1em;
        }
    </style>
{% endblock %}

{% if is_paginated %}{% load paginator %}{% endif %}

{% block content%}<div class="page-header">
    <h1>My subscriptions</h1>
</div>

{% if is_paginated %}{% paginator 2 %}{% endif %}
{% if subscriptions %}
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>User</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for user_obj in subscriptions %}
                <tr>
                    <td><a href="{% url 'user_detail' user_obj.pk %}">{{ user_obj.username }}</a></td>
                    <td>{% include 'user/unsubscribe_button.html' with unsub_user=user_obj %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% else %}
    <div class="alert alert-info">You are not subscribed to any users.</div>
{% endif %}
{% if is_paginated %}{% paginator 2 %}{% endif %}
{% endblock %}

templates/user/unsubscribe.html
{% extends "base.html" %}

{% block title%}Sure? – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block content%}
{% if form.errors %}
<div class="page-header">
<h1>What did you do?</h1>
</div>
<div class="alert alert-error">{{ form.user_id.errors }}</div>
{% else %}
<div class="page-header">
<h1>Are you sure?</h1>
</div>
<div class="well"><p>Are you sure you want to unsubscribe from <strong>{{ unsub_user.username }}</strong>? If you click yes all of your templates that have a dependency to one of <strong>{{ unsub_user.username }}</strong>'s templates won't be functional anymore.</p>
{% if dependant_templates %}</div><div class="alert alert-danger"><p>The following templates will be affected:</p>
<ul>
    {% for template in dependant_templates %}
    <li><a href="{% url 'template_edit' template.id %}">{{ template.name }}</a></li>
    {% endfor %}
</ul>
{% endif %}</div>
 <form action="{% url 'unsubscribe' %}" method="post" id="unsubscribe_form">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="btn btn-danger">Yes, I'm sure</button>
</form>
{% endif %}
{% endblock %}

templates/user/unsubscribe_button.html
<a href="{% url 'unsubscribe' %}?user_id={{ unsub_user.pk }}&amp;next={{ request.path }}{% if get_query_string %}%3F{{ get_query_string }}{% endif %}" id="unsubscribe_{{ unsub_user.pk }}" class="btn btn-danger pull-right">Unsubscribe</a>

templates/user/user_detail.html
{% extends "base.html" %}

{% block title%}User: {{ user_obj.username }} – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block userpage_li_tags %}{% if user == user_obj %} class="active"{% endif %}{% endblock %}

{% load subscribedto %}
{% load templatevisible %}
{% load addforms %}

{% block content%}
    <div class="page-header">
        <h1>{{ user_obj.username }}{% if user == user_obj %} <small>(You)</small>{% endif %}</h1>
    </div>

    {% with is_subscribed_to=request.user|subscribedto:user_obj %}
        {% if user.pk != user_obj.pk %}
            {% if not is_subscribed_to %}
                {% with subscribe_form=user_obj|subscribe_form %}
                    {% include 'user/subscribe_form.html' with sub_user=user_obj %}
                {% endwith %}
            {% else %}
                {% include 'user/unsubscribe_button.html' with unsub_user=user_obj %}
            {% endif %}
        {% endif %}

        <h2>General information</h2>
        <dl>
            <dt>Number of subscribers:</dt>
            <dd>{{ num_subscribers }}</dd>

            <dt>Number of templates:</dt>
            <dd>{{ num_templates }}</dd>

            <dt>Number of public templates:</dt>
            <dd>{{ num_public_templates }}{% if num_templates > 0 %} ({{ public_percent }}%){% endif %}</dd>

            {% if user == user_obj %}
                <dt>API token:</dt>
                {% if token %}
                <dd>{{ token }} (<a href="{% url 'api_token' %}">Create new API token</a>)</dd>
                {% else %}
                <dd><a href="{% url 'api_token' %}">Create API token</a></dd>
                {% endif %}
            {% endif %}
        </dl>

        <h2>Templates</h2>
        {% with templates=user_obj.template_set.all|getvisiblefor:user|dictsort:"name.lower" %}
            {% if templates %}
                {% include 'template/template_overview_table.html' %}
            {% else %}
                <p>This user does not have any public templates.</p>
            {% endif %}
        {% endwith %}
    {% endwith %}
{% endblock %}

templates/user/user_does_not_exist.html
{% extends "base.html" %}

{% block title%}Error – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block content %}<div class="page-header">
<h1>Error</h1>
</div>
<div class="alert alert-error">The requested user does not exist.</div>{% endblock %}

templates/user/user_list.html
{% extends "base.html" %}

{% block title%}Users – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block userlist_li_tags %} class="active"{% endblock %}

{% if is_paginated %}{% load paginator %}{% endif %}
{% load addforms %}
{% load subscribedto %}
{% load templatevisible %}

{% block content%}<div class="page-header">
    <h1>Users</h1>
</div>
{% include 'user/user_search_form.html' %}
<div class="clear"></div>
{% if is_paginated %}{% paginator 2 %}{% endif %}
<ul class="unstyled">
{% with get_query_string=request.GET.urlencode|urlencode %}
{% for user_obj in users %}
    {% with is_subscribed_to=request.user|subscribedto:user_obj %}
    <li class="well">
        {% if request.user.pk != user_obj.pk %}
            {% if not is_subscribed_to %}
                {% with subscribe_form=user_obj|subscribe_form %}
                    {% include 'user/subscribe_form.html' with sub_user=user_obj %}
                {% endwith %}
            {% else %}
                {% include 'user/unsubscribe_button.html' with unsub_user=user_obj %}
            {% endif %}
        {% endif %}
        <h2><a href="{% url 'user_detail' user_obj.pk %}">{{ user_obj.username }}</a></h2>
        {% with all_templates=user_obj.template_set.all|getvisiblefor:request.user|dictsort:"name.lower" %}
            {% if all_templates %}
                {% include 'template/template_overview_table.html' with templates=all_templates|slice:":20" %}
                {% if all_templates|length > 20 %}
                    <p><strong>Note:</strong> The list of public templates of this user has been truncated. To view the whole list visit the <a href="{% url 'user_detail' user_obj.pk %}">user page</a>.</p>
                {% endif %}
            {% else %}
                <span class="label">This user does not have any public templates.</span>
            {% endif %}
        {% endwith %}
    </li>
    {% endwith %}
{% empty %}
    <li class="alert alert-info">No users to display.</li>
{% endfor %}
{% endwith %}
</ul>
{% if is_paginated %}{% paginator 2 %}{% endif %}
{% endblock %}

templates/user/user_search_form.html
<form action="{% url 'user_list' %}" method="get" id="user_search_form" class="form-search pull-right">
    <label for="id_username">{{ user_search_form.username.label }}</label> {{ user_search_form.username }}
    <label for="id_template_name">{{ user_search_form.template_name.label }}</label>{{ user_search_form.template_name }}
    <button class="btn" type="submit">Search</button>
</form>